version: 2
workers:
- type: router
  realms:
  - name: realm1
    roles:
    - name: public
      permissions:
      - uri: ''
        match: prefix
        allow:
          call: true
          register: true
          publish: true
          subscribe: true
        disclose:
          caller: true
          publisher: true
        cache: true
  transports:
  - type: web
    endpoint:
      type: tcp
      port: 20408
    paths:
      /:
        type: static
        directory: ../web
      ws:
        type: websocket
        options:
          auto_fragment_size: 65536
        auth:
          anonymous:
            type: static
            role: public
- id: coordinator
  type: guest
  executable: /path/to/labgrid-venv/bin/python3
  arguments:
  - -m
  - labgrid.remote.coordinator
  options:
    workdir: .
    env:
      vars:
        WS: ws://localhost:20408/ws
